In [1]:
from PreProcessor import *
from sklearn.decomposition import TruncatedSVD
import numpy as np

railo
runtime
sql
exp
op
railo
runtime
sql
exp
Expression
railo
runtime
sql
exp
Expression Support
Operation
Expression Support
Operation
Expression
exp
operator
exp
Expression
get Exp
exp
operator
get Operator
operator
Operation
Expression
exp
operator
exp
exp
operator
operator
String
to String
no Alias
has Alias
no Alias
operator
OPERATION
IS
NULL
operator
OPERATION
IS
NOT
NULL
exp
to String
true
Operation
to String
operator
Operation
to String
operator
exp
to String
true
to String
true
get Alias
['railo', 'runtim', 'sql', 'exp', 'op', 'railo', 'runtim', 'sql', 'exp', 'express', 'railo', 'runtim', 'sql', 'exp', 'express', 'support', 'oper', 'express', 'support', 'oper', 'express', 'exp', 'oper', 'exp', 'express', 'get', 'exp', 'exp', 'oper', 'get', 'oper', 'oper', 'oper', 'express', 'exp', 'oper', 'exp', 'exp', 'oper', 'oper', 'string', 'to', 'string', 'no', 'alia', 'ha', 'alia', 'no', 'alia', 'oper', 'oper', 'is', 'null', 'oper', 'oper', 'is', 'not', 'null', 'exp', 'to', 'string', '

In [2]:
LSA_model = TruncatedSVD(n_components=100)
LSA_data_useCases = LSA_model.fit_transform(tfidf_useCases)
LSA_data_codes = LSA_model.fit_transform(tfidf_code)

# Sigma = lsa_obj.singular_values_
# V_T = lsa_obj.components_.T

NameError: name 'tfidf_useCases' is not defined

In [34]:
#usecases (100*usecases_nu)
#code (100*codes_nu)
#LSA_similraity_matrix (usecases_nu*codes_nu)
#d1,d2,d3,d4
#u1,u2,u3,u4
#u1*d1,u1*d2,u1*d3 ...
#d1*u1,d1*u2,d1*u3 ...
#each row coresspond between the use cases and each document
# [[d1*c1 d1*c2],[d2*c1 d2*c2]]

LSA_data_codes=np.array([[1,2,3,4,5] , [6,7,8,9,10]])
LSA_data_useCases=np.array([[11,12,13,14,15] , [16,17,18,19,21],[2,5,9,11,42]])

LSA_data_codes_norm=np.repeat(np.linalg.norm(LSA_data_codes,axis=1),LSA_data_useCases.shape[0])
LSA_data_useCases_norm=np.repeat(np.linalg.norm(LSA_data_useCases,axis=1),LSA_data_codes.shape[0])

LSA_data_codes_norm=LSA_data_codes_norm.reshape(LSA_data_codes.shape[0],LSA_data_useCases.shape[0]).T 
LSA_data_useCases_norm=LSA_data_useCases_norm.reshape(LSA_data_useCases.shape[0],LSA_data_codes.shape[0])

print(LSA_data_codes_norm)
print(LSA_data_useCases_norm)

LSA_similraity_matrix=np.dot(LSA_data_useCases,LSA_data_codes.T)/np.multiply(LSA_data_useCases_norm,LSA_data_codes_norm)

print(LSA_similraity_matrix)

[[ 7.41619849 18.16590212]
 [ 7.41619849 18.16590212]
 [ 7.41619849 18.16590212]]
[[29.24038303 29.24038303]
 [40.87786687 40.87786687]
 [44.66542287 44.66542287]]
[[0.9453431  0.99778241]
 [0.94010268 0.99652116]
 [0.8845346  0.78630721]]
